### ISSUE TITLE
Latest pre-release fails to start

### ISSUE THREAD

**Issue by haise0** [decduck3/dstguimodcreator#2]
Basically just about as described.
Running the setup was fine, but running the launcher did nothing (nor did the jar). Running the jar in the command line results with the following error:
```
Error: Unable to initialize main class Master
Caused by: java.lang.NoClassDefFoundError: com/formdev/flatlaf/FlatDarkLaf
```

Cloning the repo and building the jar fresh now.

It's a shame to see things like this get dropped because the community is small compared to other ones. I do find this super cool, though, and I'd love to see it get fleshed out and become functional at some point. I think C# may have been a better route to go, though I don't know much about java myself anyways.

Edit: I am extremely unfamiliar and inexperienced with java and other less intuitive languages and I am definitely having issues building. Attention from the dev would be much appreciated

**Comment by decduck3** [comment]
I've compiled with Java 14, it all seems to be working at the moment. 

The problems may be been with the JFrames (the window manager). I'm using IntelliJ's GUI Designer, so you need to use IntelliJ to compile the jar.

**Comment by haise0** [comment]
Ah, that'd do it.
Thanks! You can probably close this now. If your build is passing, the only thing I'm sure would be user error on my part from here (although I wouldn't mind the latest release from you either way).
